apiVersion: v1
kind: Service
metadata:
    name: airlabtc
    labels:
        app: airlabtc
spec:
    type: NodePort
    selector:
        app: airlabtc
    ports:
        - protocol: TCP
          port: 9090
          targetPort: 9090
          nodePort: 31090
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: airlabtc
    labels:
        app: airlabtc
spec:
    selector:
        matchLabels:
            app: airlabtc
    replicas: 1
    template:
        metadata:
            labels:
                app: airlabtc
        spec:
            containers:
                - name: airlabtc
                  image: airlab/tc:1.0-SNAPSHOT
                  ports:
                      - containerPort: 9090
                  env:
                      -   name: HTTP_PORT
                          value: "9090"
                      -   name: JAVA_OPTS
                          value: -server -Xss256k -Xms1024m -Xmx1024m -XX:ParallelGCThreads=1 -XX:+PerfDisableSharedMem -XX:+UseParallelOldGC -XX:CICompilerCount=2 -XX:NativeMemoryTracking=summary -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.bin -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n -Dcom.sun.management.jmxremote.port=31084 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=31084 -Djava.rmi.server.hostname=localhost